import streamlit as st
from trend_engine import generate_weekly_digest
from styles import inject_css, sidebar_nav
from datetime import datetime

st.set_page_config(page_title="Weekly Digest — AI Trends Explorer", layout="wide")
inject_css()
sidebar_nav()

st.title("Weekly Digest")
st.markdown("A structured briefing synthesized from the latest papers and news — formatted for leadership.")
st.divider()

week_num = datetime.now().isocalendar()[1]
year = datetime.now().year
date_str = datetime.now().strftime("%B %d, %Y")
st.markdown(
    f'<div style="font-family: \'Playfair Display\', serif; font-size: 1.1rem; '
    f'font-weight: 600; color: #1a1a1a; letter-spacing: -0.01em; margin-bottom: 1.5rem;">'
    f'Week {week_num} · {date_str}</div>',
    unsafe_allow_html=True
)

@st.cache_data(ttl=3600, show_spinner=False)
def load_digest():
    return generate_weekly_digest()

col_btn, col_dl, _ = st.columns([1, 1, 4])
with col_btn:
    if st.button("Regenerate", type="secondary"):
        st.cache_data.clear()
        st.rerun()

with st.spinner("Generating digest from latest signals..."):
    digest = load_digest()

with col_dl:
    st.download_button(
        label="Export .md",
        data=digest,
        file_name="ai_weekly_digest.md",
        mime="text/markdown",
    )

st.divider()
st.markdown(digest)
st.divider()
st.caption("Generated by GPT-4o-mini · Sources: arXiv + AI news feeds")